runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

service: lobie-design-front

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: 'production'

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10